### PR TITLE
feat: Added logout button

### PR DESCRIPTION
**Pull request by wrathbun**
Committing in place of Mitchell who is having issues with git
Adds a new logout button component, will clear the user's session variable and return them to the default route (home page/login page) after clicking.
Additionally, it looks like this commit added some other stuff I've been working on by accident. 
-Fixes some errors I spotted in profileAPI
-added some of the APIs to server.js
-Added some components to app.js
-Added some testing code to about.js and contact.js
I'll resolve any errors with these in the refactor
resolves issue #3

### CODE REVIEW

**Comment by josephcognata** [comment]
Looks good! Seems to resolve issue #3

**Comment by josephcognata** [comment]
Closes #3

**Comment by wrathbun** [comment]
closes #3

**Comment by wrathbun** [comment]
That didn't seem to work for some reason so I just closed it manually

**Pull request merged**
