### PR TITLE
Deleting posts

### LINKED ISSUE #65: Delete all of a user's posts (Account Settings)
As a user of cutest paw, I would like to be able to delete my posts so that I can remove this information from the website if I choose

Acceptance Criteria: 
1. On providing the user's correct password, pressing the button, and confirming the following dialogue, all of a user's posts will be deleted from the database
2. If the user's password is incorrect, display a message and do not continue
3. If the user's password is correct, display a prompt asking if they are sure they would like to continue
4. If they answer no to this prompt, do not continue

Tasks: (All Matt)
1. Delete all posts component
 1.1 Component includes fields for a user's password and a submit button
 1.2 Message if the password is incorrect and prompt asking if the user is sure they would like to continue
 1.3 Checks to ensure posts will only be deleted if a correct password was provided and the user answered yes to the prompt
2. Delete all posts API
 2.1 API to delete all posts made my a given user

### PR DESCRIPTION
**Pull request by mley1**
Added both the frontend and backend for deleting all posts associated with a user.

### CODE REVIEW

**Review by wrathbun — CHANGES_REQUESTED** [review]
A few changes and this is good to merge. I DMd you the changes

**Comment by mley1** [comment]
Fixed issues mentioned after review

**Review by wrathbun — COMMENTED** [review]
looks good!

**Review by wrathbun — COMMENTED** [review]
ready to merge

**Review by wrathbun — APPROVED** [review]

**Pull request merged**
