### PR TITLE
Backend profile

### PR DESCRIPTION
**Pull request by mley1**
Constructed the api for the backend of the profile

### CODE REVIEW

**Comment by mley1** [comment]
Everything should be ok I believe. If any issues or bugs arise, inform me asap

**Comment by wrathbun** [comment]
Your code looks good for the most part. Just 2 issues. Your APIs need to have different names and you should rename it to "profileAPI.js" and move it into the api folder

**Comment by wrathbun** [comment]
Looks good!
partially resolves issue #4

**Review by wrathbun — COMMENTED** [review]
Looks good, Actually needs one more line here and 2 in server.js that we forgot in order to use it but those can be handled later

**Pull request merged**
